//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontOffice.FinancialPlanningService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ACBALibrary")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AccountGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> AdvancedOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutorizedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChiefAccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PositionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TransactionLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort filialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong number_of_itemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int transRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong userCustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short userPermissionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountGroup {
            get {
                return this.AccountGroupField;
            }
            set {
                if ((this.AccountGroupField.Equals(value) != true)) {
                    this.AccountGroupField = value;
                    this.RaisePropertyChanged("AccountGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdvancedOptions {
            get {
                return this.AdvancedOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdvancedOptionsField, value) != true)) {
                    this.AdvancedOptionsField = value;
                    this.RaisePropertyChanged("AdvancedOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutorized {
            get {
                return this.IsAutorizedField;
            }
            set {
                if ((this.IsAutorizedField.Equals(value) != true)) {
                    this.IsAutorizedField = value;
                    this.RaisePropertyChanged("IsAutorized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChiefAcc {
            get {
                return this.IsChiefAccField;
            }
            set {
                if ((this.IsChiefAccField.Equals(value) != true)) {
                    this.IsChiefAccField = value;
                    this.RaisePropertyChanged("IsChiefAcc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManager {
            get {
                return this.IsManagerField;
            }
            set {
                if ((this.IsManagerField.Equals(value) != true)) {
                    this.IsManagerField = value;
                    this.RaisePropertyChanged("IsManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PositionID {
            get {
                return this.PositionIDField;
            }
            set {
                if ((this.PositionIDField.Equals(value) != true)) {
                    this.PositionIDField = value;
                    this.RaisePropertyChanged("PositionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionName {
            get {
                return this.PositionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionNameField, value) != true)) {
                    this.PositionNameField = value;
                    this.RaisePropertyChanged("PositionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactionLimit {
            get {
                return this.TransactionLimitField;
            }
            set {
                if ((this.TransactionLimitField.Equals(value) != true)) {
                    this.TransactionLimitField = value;
                    this.RaisePropertyChanged("TransactionLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort filialCode {
            get {
                return this.filialCodeField;
            }
            set {
                if ((this.filialCodeField.Equals(value) != true)) {
                    this.filialCodeField = value;
                    this.RaisePropertyChanged("filialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong number_of_item {
            get {
                return this.number_of_itemField;
            }
            set {
                if ((this.number_of_itemField.Equals(value) != true)) {
                    this.number_of_itemField = value;
                    this.RaisePropertyChanged("number_of_item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int transRight {
            get {
                return this.transRightField;
            }
            set {
                if ((this.transRightField.Equals(value) != true)) {
                    this.transRightField = value;
                    this.RaisePropertyChanged("transRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong userCustomerNumber {
            get {
                return this.userCustomerNumberField;
            }
            set {
                if ((this.userCustomerNumberField.Equals(value) != true)) {
                    this.userCustomerNumberField = value;
                    this.RaisePropertyChanged("userCustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short userPermissionId {
            get {
                return this.userPermissionIdField;
            }
            set {
                if ((this.userPermissionIdField.Equals(value) != true)) {
                    this.userPermissionIdField = value;
                    this.RaisePropertyChanged("userPermissionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte FinancialPlanningTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RegisteredUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Target> TargetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentData {
            get {
                return this.DocumentDataField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentDataField, value) != true)) {
                    this.DocumentDataField = value;
                    this.RaisePropertyChanged("DocumentData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte FinancialPlanningType {
            get {
                return this.FinancialPlanningTypeField;
            }
            set {
                if ((this.FinancialPlanningTypeField.Equals(value) != true)) {
                    this.FinancialPlanningTypeField = value;
                    this.RaisePropertyChanged("FinancialPlanningType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RegisteredUserID {
            get {
                return this.RegisteredUserIDField;
            }
            set {
                if ((this.RegisteredUserIDField.Equals(value) != true)) {
                    this.RegisteredUserIDField = value;
                    this.RaisePropertyChanged("RegisteredUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Target> Targets {
            get {
                return this.TargetsField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetsField, value) != true)) {
                    this.TargetsField = value;
                    this.RaisePropertyChanged("Targets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Target", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Target : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FilialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningIndicator> PlanningIndicatorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TargetTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FilialCode {
            get {
                return this.FilialCodeField;
            }
            set {
                if ((this.FilialCodeField.Equals(value) != true)) {
                    this.FilialCodeField = value;
                    this.RaisePropertyChanged("FilialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningIndicator> PlanningIndicators {
            get {
                return this.PlanningIndicatorsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanningIndicatorsField, value) != true)) {
                    this.PlanningIndicatorsField = value;
                    this.RaisePropertyChanged("PlanningIndicators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetID {
            get {
                return this.TargetIDField;
            }
            set {
                if ((this.TargetIDField.Equals(value) != true)) {
                    this.TargetIDField = value;
                    this.RaisePropertyChanged("TargetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TargetType {
            get {
                return this.TargetTypeField;
            }
            set {
                if ((this.TargetTypeField.Equals(value) != true)) {
                    this.TargetTypeField = value;
                    this.RaisePropertyChanged("TargetType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanningIndicator", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class PlanningIndicator : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningIndicatorGroup> PlanningIndicatorGroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningIndicatorGroup> PlanningIndicatorGroups {
            get {
                return this.PlanningIndicatorGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanningIndicatorGroupsField, value) != true)) {
                    this.PlanningIndicatorGroupsField = value;
                    this.RaisePropertyChanged("PlanningIndicatorGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanningIndicatorGroup", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Loan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Deposit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Card))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Other))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Target>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Target))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningIndicator>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.PlanningIndicator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningIndicatorGroup>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.ActionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.ResultCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningTypeInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.PlanningTypeInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Measure>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.Measure))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningSubTypeInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.PlanningSubTypeInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FrontOffice.FinancialPlanningService.User))]
    public partial class PlanningIndicatorGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<object> PlanningIndicatorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<object> PlanningIndicatorDetails {
            get {
                return this.PlanningIndicatorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanningIndicatorDetailsField, value) != true)) {
                    this.PlanningIndicatorDetailsField = value;
                    this.RaisePropertyChanged("PlanningIndicatorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ActualQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlanningIndicatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TargetQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ActualQuantity {
            get {
                return this.ActualQuantityField;
            }
            set {
                if ((this.ActualQuantityField.Equals(value) != true)) {
                    this.ActualQuantityField = value;
                    this.RaisePropertyChanged("ActualQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanningIndicatorID {
            get {
                return this.PlanningIndicatorIDField;
            }
            set {
                if ((this.PlanningIndicatorIDField.Equals(value) != true)) {
                    this.PlanningIndicatorIDField = value;
                    this.RaisePropertyChanged("PlanningIndicatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TargetQuantity {
            get {
                return this.TargetQuantityField;
            }
            set {
                if ((this.TargetQuantityField.Equals(value) != true)) {
                    this.TargetQuantityField = value;
                    this.RaisePropertyChanged("TargetQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loan", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Loan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ActualPortfolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlanningIndicatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TargetPortfolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ActualPortfolio {
            get {
                return this.ActualPortfolioField;
            }
            set {
                if ((this.ActualPortfolioField.Equals(value) != true)) {
                    this.ActualPortfolioField = value;
                    this.RaisePropertyChanged("ActualPortfolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanningIndicatorID {
            get {
                return this.PlanningIndicatorIDField;
            }
            set {
                if ((this.PlanningIndicatorIDField.Equals(value) != true)) {
                    this.PlanningIndicatorIDField = value;
                    this.RaisePropertyChanged("PlanningIndicatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TargetPortfolio {
            get {
                return this.TargetPortfolioField;
            }
            set {
                if ((this.TargetPortfolioField.Equals(value) != true)) {
                    this.TargetPortfolioField = value;
                    this.RaisePropertyChanged("TargetPortfolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deposit", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Deposit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> ActualPortfolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlanningIndicatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TargetPortfolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> ActualPortfolio {
            get {
                return this.ActualPortfolioField;
            }
            set {
                if ((this.ActualPortfolioField.Equals(value) != true)) {
                    this.ActualPortfolioField = value;
                    this.RaisePropertyChanged("ActualPortfolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanningIndicatorID {
            get {
                return this.PlanningIndicatorIDField;
            }
            set {
                if ((this.PlanningIndicatorIDField.Equals(value) != true)) {
                    this.PlanningIndicatorIDField = value;
                    this.RaisePropertyChanged("PlanningIndicatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TargetPortfolio {
            get {
                return this.TargetPortfolioField;
            }
            set {
                if ((this.TargetPortfolioField.Equals(value) != true)) {
                    this.TargetPortfolioField = value;
                    this.RaisePropertyChanged("TargetPortfolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Card : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ActualQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlanningIndicatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TargetQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ActualQuantity {
            get {
                return this.ActualQuantityField;
            }
            set {
                if ((this.ActualQuantityField.Equals(value) != true)) {
                    this.ActualQuantityField = value;
                    this.RaisePropertyChanged("ActualQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanningIndicatorID {
            get {
                return this.PlanningIndicatorIDField;
            }
            set {
                if ((this.PlanningIndicatorIDField.Equals(value) != true)) {
                    this.PlanningIndicatorIDField = value;
                    this.RaisePropertyChanged("PlanningIndicatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TargetQuantity {
            get {
                return this.TargetQuantityField;
            }
            set {
                if ((this.TargetQuantityField.Equals(value) != true)) {
                    this.TargetQuantityField = value;
                    this.RaisePropertyChanged("TargetQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Other", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Other : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ActualQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlanningIndicatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TargetPercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TargetQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ActualQuantity {
            get {
                return this.ActualQuantityField;
            }
            set {
                if ((this.ActualQuantityField.Equals(value) != true)) {
                    this.ActualQuantityField = value;
                    this.RaisePropertyChanged("ActualQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanningIndicatorID {
            get {
                return this.PlanningIndicatorIDField;
            }
            set {
                if ((this.PlanningIndicatorIDField.Equals(value) != true)) {
                    this.PlanningIndicatorIDField = value;
                    this.RaisePropertyChanged("PlanningIndicatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TargetPercent {
            get {
                return this.TargetPercentField;
            }
            set {
                if ((this.TargetPercentField.Equals(value) != true)) {
                    this.TargetPercentField = value;
                    this.RaisePropertyChanged("TargetPercent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TargetQuantity {
            get {
                return this.TargetQuantityField;
            }
            set {
                if ((this.TargetQuantityField.Equals(value) != true)) {
                    this.TargetQuantityField = value;
                    this.RaisePropertyChanged("TargetQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionResult", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class ActionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FrontOffice.FinancialPlanningService.ResultCode ResultCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FrontOffice.FinancialPlanningService.ResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultCode", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    public enum ResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Normal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanningTypeInfo", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class PlanningTypeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Measure> MeasuresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningSubTypeInfo> SubTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Measure> Measures {
            get {
                return this.MeasuresField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasuresField, value) != true)) {
                    this.MeasuresField = value;
                    this.RaisePropertyChanged("Measures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((this.ParentField.Equals(value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningSubTypeInfo> SubTypes {
            get {
                return this.SubTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTypesField, value) != true)) {
                    this.SubTypesField = value;
                    this.RaisePropertyChanged("SubTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Measure", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class Measure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanningSubTypeInfo", Namespace="http://schemas.datacontract.org/2004/07/PlannedTargets")]
    [System.SerializableAttribute()]
    public partial class PlanningSubTypeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Measure> MeasuresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<FrontOffice.FinancialPlanningService.Measure> Measures {
            get {
                return this.MeasuresField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasuresField, value) != true)) {
                    this.MeasuresField = value;
                    this.RaisePropertyChanged("Measures");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinancialPlanningService.IFinancialPlanningService")]
    public interface IFinancialPlanningService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/SetCurrentUser", ReplyAction="http://tempuri.org/IFinancialPlanningService/SetCurrentUserResponse")]
        void SetCurrentUser(FrontOffice.FinancialPlanningService.User currentUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/SetCurrentUser", ReplyAction="http://tempuri.org/IFinancialPlanningService/SetCurrentUserResponse")]
        System.Threading.Tasks.Task SetCurrentUserAsync(FrontOffice.FinancialPlanningService.User currentUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/SetClientIp", ReplyAction="http://tempuri.org/IFinancialPlanningService/SetClientIpResponse")]
        void SetClientIp(string clientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/SetClientIp", ReplyAction="http://tempuri.org/IFinancialPlanningService/SetClientIpResponse")]
        System.Threading.Tasks.Task SetClientIpAsync(string clientIp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/Save", ReplyAction="http://tempuri.org/IFinancialPlanningService/SaveResponse")]
        FrontOffice.FinancialPlanningService.ActionResult Save(FrontOffice.FinancialPlanningService.Document document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/Save", ReplyAction="http://tempuri.org/IFinancialPlanningService/SaveResponse")]
        System.Threading.Tasks.Task<FrontOffice.FinancialPlanningService.ActionResult> SaveAsync(FrontOffice.FinancialPlanningService.Document document);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/GetPlanningTypes", ReplyAction="http://tempuri.org/IFinancialPlanningService/GetPlanningTypesResponse")]
        System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningTypeInfo> GetPlanningTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/GetPlanningTypes", ReplyAction="http://tempuri.org/IFinancialPlanningService/GetPlanningTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningTypeInfo>> GetPlanningTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanningTypes", ReplyAction="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanningTypesResponse")]
        System.Collections.Generic.Dictionary<string, int> GetFinancialPlanningTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanningTypes", ReplyAction="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanningTypesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetFinancialPlanningTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanning", ReplyAction="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanningResponse")]
        FrontOffice.FinancialPlanningService.Document GetFinancialPlanning(FrontOffice.FinancialPlanningService.Document document, System.DateTime year, int filialCode, System.Nullable<int> setNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanning", ReplyAction="http://tempuri.org/IFinancialPlanningService/GetFinancialPlanningResponse")]
        System.Threading.Tasks.Task<FrontOffice.FinancialPlanningService.Document> GetFinancialPlanningAsync(FrontOffice.FinancialPlanningService.Document document, System.DateTime year, int filialCode, System.Nullable<int> setNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinancialPlanningServiceChannel : FrontOffice.FinancialPlanningService.IFinancialPlanningService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialPlanningServiceClient : System.ServiceModel.ClientBase<FrontOffice.FinancialPlanningService.IFinancialPlanningService>, FrontOffice.FinancialPlanningService.IFinancialPlanningService {
        
        public FinancialPlanningServiceClient() {
        }
        
        public FinancialPlanningServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialPlanningServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialPlanningServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialPlanningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetCurrentUser(FrontOffice.FinancialPlanningService.User currentUser) {
            base.Channel.SetCurrentUser(currentUser);
        }
        
        public System.Threading.Tasks.Task SetCurrentUserAsync(FrontOffice.FinancialPlanningService.User currentUser) {
            return base.Channel.SetCurrentUserAsync(currentUser);
        }
        
        public void SetClientIp(string clientIp) {
            base.Channel.SetClientIp(clientIp);
        }
        
        public System.Threading.Tasks.Task SetClientIpAsync(string clientIp) {
            return base.Channel.SetClientIpAsync(clientIp);
        }
        
        public FrontOffice.FinancialPlanningService.ActionResult Save(FrontOffice.FinancialPlanningService.Document document) {
            return base.Channel.Save(document);
        }
        
        public System.Threading.Tasks.Task<FrontOffice.FinancialPlanningService.ActionResult> SaveAsync(FrontOffice.FinancialPlanningService.Document document) {
            return base.Channel.SaveAsync(document);
        }
        
        public System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningTypeInfo> GetPlanningTypes() {
            return base.Channel.GetPlanningTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<FrontOffice.FinancialPlanningService.PlanningTypeInfo>> GetPlanningTypesAsync() {
            return base.Channel.GetPlanningTypesAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetFinancialPlanningTypes() {
            return base.Channel.GetFinancialPlanningTypes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetFinancialPlanningTypesAsync() {
            return base.Channel.GetFinancialPlanningTypesAsync();
        }
        
        public FrontOffice.FinancialPlanningService.Document GetFinancialPlanning(FrontOffice.FinancialPlanningService.Document document, System.DateTime year, int filialCode, System.Nullable<int> setNumber) {
            return base.Channel.GetFinancialPlanning(document, year, filialCode, setNumber);
        }
        
        public System.Threading.Tasks.Task<FrontOffice.FinancialPlanningService.Document> GetFinancialPlanningAsync(FrontOffice.FinancialPlanningService.Document document, System.DateTime year, int filialCode, System.Nullable<int> setNumber) {
            return base.Channel.GetFinancialPlanningAsync(document, year, filialCode, setNumber);
        }
    }
}
